[project]
name = "stargazer"
version = "0.1.0"
description = "API to retrieve neighbor repositories on GitHub"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.124.4",
    "python-dotenv>=1.2.1",
]
